### ISSUE TITLE
Max-integer-value check too specific

### ISSUE THREAD

**Issue by myersjustinc** [dataproofer/core-suite#6]
I'm a big fan of the idea of checking for suspicious integer values, but [the one currently provided][current-check] is very specific and not one I've encountered in other software packages.

This isn't to say your number's wrong, of course—clearly it's bitten you in the past—but I'd like to suggest adding a few other values that have caused issues for me. My main suggestion would be to add **2,147,483,647**.

## Expected values ##

[The MySQL docs][mysql] docs list the values I'm more accustomed to:

|Type     |Storage (Bytes)|Minimum Value (Signed/Unsigned)|Maximum Value (Signed/Unsigned)|
|---------|---------------|-------------------------------|-------------------------------|
|TINYINT  |1              |-128                           |127                            |
|         |               |0                              |255                            |
|SMALLINT |2              |-32768                         |32767                          |
|         |               |0                              |65535                          |
|MEDIUMINT|3              |-8388608                       |8388607                        |
|         |               |0                              |16777215                       |
|INT      |4              |-2147483648                    |2147483647                     |
|         |               |0                              |4294967295                     |
|BIGINT   |8              |-9223372036854775808           |9223372036854775807            |
|         |               |0                              |18446744073709551615           |

In particular, you might recognize values like:

*   **65,535**: max unsigned value for a `SMALLINT`, which is one less than the [Excel row cutoff][excel-rows] (since counting from 0 to 65,535 gives you 65,536 rows)

*   **16,777,215**: max unsigned value for a `MEDIUMINT`, which is the maximum number of colors in eight-bit RGB (eight bits each for red, green and blue), and why you'll hear references to "[16 million colors][16-million]"

*   **2,147,483,647**: the one I'm most used to, because it's the max signed value for an `INT`, and rose to fame a year or two back when Gangnam Style [maxed out Google's 32-bit signed view counter][gangnam-style].

(If you're more of a Postgres fan, [their docs][postgresql] list some of the same values.)

## Theory ##

These maximum values tend to appear because their binary representations are:

*   all ones, for the maximum value of an unsigned integer (only zero or positive), such as 65,535, which is `1111 1111 1111 1111`

*   a zero followed by all ones, for the maximum value of a signed integer (can be zero, positive or negative), such as 32,767, which is `0111 1111 1111 1111`, or 2,147,483,647, which is `0111 1111 1111 1111 1111 1111 1111 1111`

*   a one followed by all zeroes for the minimum (i.e., most negative) value of a signed integer, such as -32,768, which has a [two's complement][twos-complement] representation of `1000 0000 0000 0000`

These mostly apply for binary values with some multiple of eight bits (i.e., an integral number of bytes), such as my 16-bit examples (and one 32-bit example) here.

## Concern ##

The [current check][current-check] for a value of 2,097,152 is an interesting one because it _doesn't_ hit a nice, round number of bytes: `10 0000 0000 0000 0000 0000` doesn't seem to meet these conditions.

Again, this isn't to say it's not a problematic value—clearly it has been for you—but I'd argue the values above (in particular **2,147,483,647**, as the default max signed integer value for both MySQL and Postgres) are more likely to suggest problems for other users.

## Implementation ##

I'm happy to add a few more hardcoded values in a PR if you'd like, but I figured I'd start the conversation first in case there are other values people would like to suggest.

[16-million]: http://gizmodo.com/all-16-million-colors-of-the-rgb-spectrum-are-in-these-1330219443
[current-check]: https://github.com/dataproofer/core-suite/blob/764d1d19e492eb29c79bf8f1c6a740246d2cf585/src/integerEquals2097152.js#L29
[excel-rows]: https://github.com/dataproofer/core-suite/blob/764d1d19e492eb29c79bf8f1c6a740246d2cf585/src/numberOfRowsIs65k.js
[gangnam-style]: http://edition.cnn.com/2014/12/03/showbiz/gangnam-style-youtube/index.html?hpt=hp_t4
[mysql]: https://dev.mysql.com/doc/refman/5.7/en/integer-types.html
[postgresql]: http://www.postgresql.org/docs/9.5/interactive/datatype-numeric.html#DATATYPE-NUMERIC-TABLE
[twos-complement]: https://en.wikipedia.org/wiki/Two%27s_complement

**Comment by geraldarthur** [comment]
Hey! Thank you for the extremely helpful comments. I've gone ahead and updated the [`max-int` branch](https://github.com/dataproofer/core-suite/tree/max-int) to include a test for **2,147,483,647**. 

Would you be interested in writing a `bigint` or `smallint` test? If you have a second, we're looking for more feedback on the test editing/creation process. We'd be thrilled if you'd want to jot out a test or two and kept us in the loop.

**2,097,152** was first pointed out in the [ProPublica Data Bulletproofing](https://github.com/propublica/guides/blob/master/data-bulletproofing.md#integrity-checks-for-every-data-set) readme. I've added that sourcing to the documentation in the `max-int` branch, too.

Have you encountered that specific max int problem before, though? We were inspired in part by that guide and your Handguns & Tequila SRCCON panel notes, so please keep the feedback coming! We really appreciate it.

**Comment by myersjustinc** [comment]
Ah, that sourcing makes sense—thanks!

I haven't encountered the 2,097,152 value before, but I've definitely run into 2,147,483,647 before, especially in data sets involving finances such as university endowments. (Wrote that number nice and big on the data team whiteboard at The Chronicle of Higher Education after it bit us a few times when we were loading up our internal copy of [IPEDS](http://nces.ed.gov/ipeds).)

(In that particular case, of course, Dataproofer wouldn't have caught it—the CSVs from the Department of Education were right, but the error was introduced when we tried to load it into our MySQL server.)

Quick procedural question: If I create a new test for `bigint` and another for `smallint`, should I be creating new copies of [maxInteger.js](https://github.com/dataproofer/core-suite/blob/a7db4ce8c5561cf7cc5b85998d2c4382af9a0f8b/src/maxInteger.js) for example, and just changing a couple of lines, or should we refactor this somehow so `maxInteger.js` can detect several of these common values?

**Comment by geraldarthur** [comment]
Interesting, and you're right. The current app couldn't catch that bug. However, we're just barely starting to discuss where we grow the Dataproofer project from here. Happy to talk more if you think there's a need.

For now, creating copies of tests is exactly how we do it. It's relatively simple for newer coders, but (hopefully) quick and easy for more experienced folks like yourself. Thanks again for your time!

**Comment by geraldarthur** [comment]
Cleaned up and merged in your code. Thanks again! I'll also get a contributors file going to help say thanks and give credit where credit is due. For now, there's no next actions for this issue so I'll close it out. Cheers!
